/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package saga.sample;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.eventuate.common.json.mapper.JSonMapper;
import org.springframework.context.annotation.Primary;

@SpringBootApplication
public class App {
    @Bean
    @Primary // conflicts with _halObjectMapper
    public ObjectMapper objectMapper() {
        return JSonMapper.objectMapper;
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
